name: Build and Publish
run-name: ${{ github.ref_name }} (Build and Publish)

on:
  push:
    tags:
      - '*/*'

env:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_CLI_EXPERIMENTAL: enabled
  CI_TAG: ${{ github.ref_name }}

permissions:
  contents: read

jobs:
  publish_images:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: linuxamd64
            name: linux/amd64
          - image: linuxarm32v7
            name: linux/arm/v7
          - image: linuxarm64v8
            name: linux/arm64/v8
          - image: buildx
            name: buildx image
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Publish image
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        shell: bash
        run: .github/scripts/run-image.sh "${{ matrix.image }}" publish

  publish_multiarch:
    name: Publish multi-arch manifest
    runs-on: ubuntu-latest
    needs: publish_images
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Publish manifest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        shell: bash
        run: .github/scripts/publish-manifest.sh
