name: Publish Docker Images

on:
  push:
    tags:
      - '*/*'

env:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}

jobs:
  publish_linuxamd64:
    name: Publish linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish image
        shell: bash
        run: |
          source ".github/scripts/parse-tag.sh"
          DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_AMD64"
          DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG-amd64"
          if [ -f "$DOCKERHUB_DOCKEFILE" ]; then
              source ".github/scripts/push-image.sh"
          else
              echo "Skipping linuxamd64 because $DOCKERHUB_DOCKEFILE is not found"
          fi

  publish_linuxarm32v7:
    name: Publish linux/arm/v7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish image
        shell: bash
        run: |
          source ".github/scripts/parse-tag.sh"
          DOCKER_ARGS=()
          if [ -n "$DOCKER_OPTIONS" ]; then
              DOCKER_ARGS=("$DOCKER_OPTIONS")
          fi
          DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_ARM32"
          DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG-arm32v7"
          if [ -f "$DOCKERHUB_DOCKEFILE" ]; then
              sudo docker "${DOCKER_ARGS[@]}" run --rm --privileged multiarch/qemu-user-static:register --reset
              if grep "#EnableQEMU" "$DOCKERHUB_DOCKEFILE"; then
                  sudo apt update
                  sudo apt install -y qemu-user-static qemu-user binfmt-support
                  sudo cp /usr/bin/qemu-arm-static "$(dirname "$DOCKERHUB_DOCKEFILE")/qemu-arm-static"
                  sed -i -e 's/#EnableQEMU //g' "$DOCKERHUB_DOCKEFILE"
              fi
              source ".github/scripts/push-image.sh"
          else
              echo "Skipping linuxarm32v7 because $DOCKERHUB_DOCKEFILE is not found"
          fi

  publish_linuxarm64v8:
    name: Publish linux/arm64/v8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish image
        shell: bash
        run: |
          source ".github/scripts/parse-tag.sh"
          DOCKER_ARGS=()
          if [ -n "$DOCKER_OPTIONS" ]; then
              DOCKER_ARGS=("$DOCKER_OPTIONS")
          fi
          DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_ARM64"
          DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG-arm64v8"
          if [ -f "$DOCKERHUB_DOCKEFILE" ]; then
              sudo docker "${DOCKER_ARGS[@]}" run --rm --privileged multiarch/qemu-user-static:register --reset
              sudo apt update
              sudo apt install -y qemu-user-static qemu-user binfmt-support
              sudo cp /usr/bin/qemu-aarch64-static "$(dirname "$DOCKERHUB_DOCKEFILE")/qemu-aarch64-static"
              sed -i -e 's/#EnableQEMU //g' "$DOCKERHUB_DOCKEFILE"
              source ".github/scripts/push-image.sh"
          else
              echo "Skipping linuxarm64v8 because $DOCKERHUB_DOCKEFILE is not found"
          fi

  publish_buildx:
    name: Publish buildx image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish image
        shell: bash
        run: |
          source ".github/scripts/parse-tag.sh"
          DOCKERHUB_DOCKEFILE="$DOCKERHUB_DOCKEFILE_BUILDX"
          DOCKERHUB_DESTINATION="$DOCKERHUB_REPO:$LATEST_TAG"
          if [ -f "$DOCKERHUB_DOCKEFILE" ]; then
              source ".github/scripts/push-image-buildx.sh"
          else
              echo "Skipping buildx because $DOCKERHUB_DOCKEFILE_BUILDX is not found"
          fi

  publish_multiarch:
    name: Publish multi-arch manifest
    runs-on: ubuntu-latest
    needs:
      - publish_linuxamd64
      - publish_linuxarm32v7
      - publish_linuxarm64v8
      - publish_buildx
    steps:
      - uses: actions/checkout@v4

      - name: Publish manifest
        shell: bash
        run: |
          source ".github/scripts/parse-tag.sh"
          DOCKER_ARGS=()
          if [ -n "$DOCKER_OPTIONS" ]; then
              DOCKER_ARGS=("$DOCKER_OPTIONS")
          fi
          sudo docker "${DOCKER_ARGS[@]}" login --username="$DOCKERHUB_USER" --password="$DOCKERHUB_PASS"
          IMAGES=()
          if [ -f "$DOCKERHUB_DOCKEFILE_AMD64" ]; then
              IMAGES+=("$DOCKERHUB_DESTINATION-amd64")
          fi
          if [ -f "$DOCKERHUB_DOCKEFILE_ARM64" ]; then
              IMAGES+=("$DOCKERHUB_DESTINATION-arm64v8")
          fi
          if [ -f "$DOCKERHUB_DOCKEFILE_ARM32" ]; then
              IMAGES+=("$DOCKERHUB_DESTINATION-arm32v7")
          fi
          if [ "${#IMAGES[@]}" -eq 0 ]; then
              echo "Skipping $DOCKERHUB_DESTINATION as there were no supported platforms to build for"
          else
              sudo docker manifest create --amend "$DOCKERHUB_DESTINATION" "${IMAGES[@]}"
              if [ -f "$DOCKERHUB_DOCKEFILE_AMD64" ]; then
                  sudo docker "${DOCKER_ARGS[@]}" manifest annotate "$DOCKERHUB_DESTINATION" "$DOCKERHUB_DESTINATION-amd64" --os linux --arch amd64
              fi
              if [ -f "$DOCKERHUB_DOCKEFILE_ARM32" ]; then
                  sudo docker "${DOCKER_ARGS[@]}" manifest annotate "$DOCKERHUB_DESTINATION" "$DOCKERHUB_DESTINATION-arm32v7" --os linux --arch arm --variant v7
              fi
              if [ -f "$DOCKERHUB_DOCKEFILE_ARM64" ]; then
                  sudo docker "${DOCKER_ARGS[@]}" manifest annotate "$DOCKERHUB_DESTINATION" "$DOCKERHUB_DESTINATION-arm64v8" --os linux --arch arm64 --variant v8
              fi
              sudo docker "${DOCKER_ARGS[@]}" manifest push "$DOCKERHUB_DESTINATION" -p
          fi
